ALTER TABLE devis ADD COLUMN IF NOT EXISTS artisan_id UUID REFERENCES artisans(id) ON DELETE SET NULL;
ALTER TABLE devis ADD COLUMN IF NOT EXISTS lot TEXT;
ALTER TABLE devis ADD COLUMN IF NOT EXISTS fichier_url TEXT;
ALTER TABLE factures ADD COLUMN IF NOT EXISTS artisan_id UUID REFERENCES artisans(id) ON DELETE SET NULL;
ALTER TABLE factures ADD COLUMN IF NOT EXISTS lot TEXT;
ALTER TABLE factures ADD COLUMN IF NOT EXISTS fichier_url TEXT;
